---
output: _output.yaml
---

## {data-background="img/regex_cover_image.png"}

## Connect With Us

<hr>

- Website     (https://www.rsquaredacademy.com/)
- Free Online R Courses   (https://rsquared-academy.thinkific.com/)
- R Packages  (https://pkgs.rsquaredacademy.com)
- Shiny Apps  (https://apps.rsquaredacademy.com)
- Blog        (https://blog.rsquaredacademy.com)
- GitHub      (https://github.com/rsquaredacademy)
- YouTube     (https://www.youtube.com/user/rsquaredin/)
- Twitter     (https://twitter.com/rsquaredacademy)
- Facebook    (https://www.facebook.com/rsquaredacademy/)
- Linkedin    (https://in.linkedin.com/company/rsquared-academy)

## Resources

<hr>

- <a href="https://slides.rsquaredacademy.com/decision-trees/trees.html" target="_blank">Slides</a>
- <a href="https://github.com/rsquaredacademy-education/online-courses/tree/master/decision-trees-in-r" target="_blank">Code & Data</a>
- <a href="https://rstudio.cloud/project/356612" target="_blank">RStudio Cloud</a>

## {data-background="img/ws_agenda.png"}

<br>
<br>
<br>
<br>

- what is a decision tree?


## {data-background="img/ws_section_intro.png"}

## What?

<hr>

## Classification

<hr>

<hr>

## Finding the Split

<hr>

## Splitting on Numeric Variable

<hr>

## Splitting on Categorical Variable

<hr>

## Handling Missing Values

<hr>

## Growing the Tree

<hr>

## Effectiveness of the Tree

<hr>

## Choosing the best Split

<hr>

- Gini
- Entropy
- Information Gain Ratio
- Chi Square Test
- Reduction in Variance
- F Test

## Gini 

<hr>

## Entropy

<hr>

## Information Gain Ratio

<hr>

## Chi-Square Test

<hr>

## Reduction in Variance

<hr>

## F Test

<hr>

## Pruning

<hr>

## Extracting Rules

<hr>
 
## Summary

<hr>

## References

<hr>

## {data-background="img/thankyou.png"}
