---
title: "ggplot2: Positioning Geoms"
output: 
  revealjs::revealjs_presentation:
    transition: slide
    incremental: true
    theme: moon
    highlight: monochrome
    center: true
    fig_width: 6
    fig_height: 5
    reveal_options:
      slideNumber: true
      previewLinks: true
---

## Intro

In this module, we will learn to position the geoms to avoid overlapping.

## Installation

```{r show, eval=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r load, echo=FALSE, eval=TRUE, results='hide', message=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
```

## Dodge

----

Preserve the vertical position while adjusting the horizontal position.

Create grouped bar plots.

----

```{r pos2}
ggplot(data = mtcars, aes(factor(cyl), fill = factor(vs))) +
  geom_bar()
```

----

```{r pos3}
ggplot(data = mtcars, aes(factor(cyl), fill = factor(vs))) +
  geom_bar(position = position_dodge(width = 1))
```

## Jitter

----

Add some noise to data points for better visualization.

```{r pos4}
ggplot(data = mtcars, aes(am, vs)) +
  geom_jitter()
```

----

```{r pos5}
ggplot(data = mtcars, aes(factor(am), factor(vs))) +
  geom_jitter()
```

----

```{r pos6}
ggplot(data = mtcars, aes(factor(am), factor(vs))) +
  geom_jitter(position = position_jitter(width = 0.1, height = 0.1))
```

----

```{r pos7}
ggplot(data = mtcars, aes(factor(am), factor(vs))) +
  geom_jitter(position = position_jitter(width = 0.05, height = 0.3))
```

----

```{r pos8}
ggplot(data = mtcars, aes(am, vs)) +
  geom_jitter(position = position_jitter(width = 0.1, height = 0.1))
```

## Nudge

----

Use with geom_text. Useful for adjusting text around points.

----

```{r pos9}
df <- data.frame(
  x = c(1,3,2,5),
  y = c("a","c","d","c")
)
```

----

```{r pos12}
ggplot(df, aes(x, y)) +
  geom_point() +
  geom_text(aes(label = y),
            position = position_nudge(y = -0.1, x = -0.2))
```

## Fill

----

Proportional bar plots.

----

```{r pos10}
ggplot(data = mtcars, aes(factor(cyl), fill = factor(gear))) +
  geom_bar(position = "fill")
```

## Stack

----

```{r pos11}
series <- data.frame(
  time = c(rep(1, 4),rep(2, 4), rep(3, 4), rep(4, 4)),
  type = rep(c('a', 'b', 'c', 'd'), 4),
  value = rpois(16, 10)
)

series$type2 <- factor(series$type, levels = c('c', 'b', 'd', 'a'))
```

----

```{r pos13}
ggplot(series, aes(time, value, group = type)) +
  geom_line(aes(colour = type)) +
  geom_point(aes(colour = type))
```

----

```{r pos14}
ggplot(series, aes(time, value, group = type)) +
  geom_line(aes(colour = type), position = "stack") +
  geom_point(aes(colour = type), position = "stack")
```

## Summary

## Next Steps..