---
output: _output.yaml
---

## {data-background="forcats.png"}

## Agenda

<hr>

- what is version control?
- what is git?
- what is github?
- pre-requisites


## git config

<hr>

Version control is a system that records changes to a file or set of files so
that you can recall specific versions later. It allows us to:

- create backups
- track every individual change made
- track who made the changes
- work collaboratively
- prevent concurrent work from conflicting

## git clone

<hr>

So what is Git? It is

- a distributed version control system
- free
- open source
- easy to learn
- flexible
- secure

## git remote

<hr>

GitHub acts as a remote host for your Git managed projects. It

- allows others to see your work
- suggest changes
- collaborate
- has a well designed web interface

## git add

<hr>

- [R](https://www.r-project.org/)
- [RStudio](https://www.rstudio.com/)

## git commit

<hr>

## git status

<hr>

## git log

<hr>

## git diff

<hr>

## git push

<hr>

## git fetch

<hr>

## git merge

<hr>

## git pull

<hr>

## git branch

<hr>

## git rebase

<hr>

## git reset

<hr>

## {data-background="thankyou.png"}
