---
output: _output.yaml
---

## {data-background="forcats.png"}

## Agenda

<hr>

- create repository
- clone repository
- add files
- create report
- push changes
- browse your project website


## Create Repository

<hr>

Version control is a system that records changes to a file or set of files so
that you can recall specific versions later. It allows us to:

- create backups
- track every individual change made
- track who made the changes
- work collaboratively
- prevent concurrent work from conflicting

## Clone Repository

<hr>

So what is Git? It is

- a distributed version control system
- free
- open source
- easy to learn
- flexible
- secure

## Add Files

<hr>

GitHub acts as a remote host for your Git managed projects. It

- allows others to see your work
- suggest changes
- collaborate
- has a well designed web interface

## Create Report

<hr>

- [R](https://www.r-project.org/)
- [RStudio](https://www.rstudio.com/)

## Push Changes

<hr>

## Browse Project Website

<hr>

## {data-background="thankyou.png"}
