---
output: _output.yaml
---

## {data-background="git_banner.png"}

## Agenda

<hr>

- new projects
- existing projects
- GitHub tour
- GitHub pages

## New Projects

<hr>

- create repository on GitHub
- clone repository using RStudio
- make some changes
- push changes to remote repository
- make changes in GitHub
- pull changes from remote repository

## Existing Projects

<hr>

- create repository in GitHub
- clone repository using RStudio
- move files from existing project
- stage, commit and push
- check remote repository

## GitHub Tour

<hr>

- your profile
- organisation
- gist
- issues
- projects
- pull requests
- wiki
- commits
- branch
- contributor
- releases
- fork

## Github Pages

<hr>

- personal/project websites
- hosted from GitHub repositories
- create a new repository `username.github.io`
- use <a href="" target="_blank">RMarkdown</a> or <a href=""
  target="_blank">Blogdown</a> to create website
- push changes to the remote repository
- visit `https://username.github.io` to view your website

## {data-background="thankyou.png"}
