---
output: _output.yaml
---

## {data-background="shell_banner.png"}

## Agenda

<hr>

- launch terminal/shell
- use terminal in RStudio
- run command from R using system()
- run shell script
- file management
- system management
- navigating file system
- help/documentation
- compression commands
- keyboard shortcuts
- search & regular expressions
- input/output
- network
- funny commands
- others

## File Management

<hr>

- cp/copy
- mv/move
- rm/del/erase
- comp/fc
- replace
- ren
- diff
- type

## System Management

<hr>

- shutdown
- free
- df
- uname
- sudo
- touch

## Navigating File System

<hr>

- ls/dir
- cd/pwd
- mkdir/md
- rmdir/rd

## Help/Documentation

<hr>

- man
- whatis
- history

## Compression Commands

<hr>

- tar
- unzip
- gzip

## Keyboard Shortcuts

<hr>

- Ctrl + C
- Ctrl + D
- Ctrl + W
- Ctrl + U
- Ctrl + R

## Search & Regular Expressions

<hr>

- grep
- find
- locate
- which
- findstr
- where

## Input/Output

<hr>

- echo
- pr
- cat
- head
- tail
- more
- less
- sort
- wc
- cls/clear

## Network

<hr>

- wget
- curl
- hostname
- ping
- nslookup

## User Information

<hr>

- finger
- groups
- who/w
- whoami

## Funny Commands

<hr>

- fortune
- yes
- banner
- rev

## Others

<hr>

- exit
- date
- time
- color
- cal
- start
- sleep


## References

<hr>

- http://www2.imm.dtu.dk/courses/02333/cygwin_tutorial/index.html
- https://tutorial.djangogirls.org/en/intro_to_command_line/
- https://ss64.com/
- https://www.learnenough.com/command-line-tutorial

## {data-background="thankyou.png"}
